apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app
  labels:
    app: wisecow
spec:
  replicas: 3  # Number of replicas for load balancing
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow-app
          image: <your_dockerhub_username>/wisecow-app:latest  # Replace with your Docker Hub username
          ports:
            - containerPort: 3000  # The port your application runs on
          env:  # Define environment variables if needed
            - name: NODE_ENV
              value: "production"
